### ISSUE TITLE
how to me can use that 

### ISSUE THREAD

**Issue by l3th2nh** [heavybeard/paypal-popup#1]
hi  , i dowload and install your plugin , i also config that in admin , but i dont know how to me can display that on frontend , can you help me fix that ?

Thanks

**Comment by heavybeard** [comment]
Hi @l3th2nh,
this is a test script. I created this plugin only for practise so I cannot ensure that it works parfectly on a Wordpress site with a different theme from my.

If you want to show the popup, you must type this script on the frontend point.
I use it on the `footer.php` file

```php
if (function_exists('payPal_popup')
    payPal_popup();
```
